name: Build

# change to "push" to build each commit
# (seems to eat through LFS data quota like there's no tomorrow)
on: workflow_dispatch

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  SHA: ${GITHUB_SHA:8}

jobs:
  version:
    uses: ./.github/workflows/versioner.yml
    with:
      type: dev

  build:
    needs: version
    uses: ./.github/workflows/builder.yml
    with:
      version: ${{ needs.version.outputs.version }}
    secrets:
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
